name: bmed365
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipython
  - ipykernel
  - ipywidgets
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - git
  - pip
  - pip:
    - gdown
    - pycaret
    - shap
    - catboost
    - xgboost
    - pyreadstat
    - statsmodels
    - pingouin
    - voila
    - scikit-learn
    - scikit-image
    - SimpleITK
    - itkwidgets
    - imageio
    - dcm2niix
    - readimc
    - tiffile
    - nilearn
    - networkx
    - dipy
    - openpyxl
    - tqdm
    - PyWavelets


## Configure the Conda-environment bmed365 for data analysis, computational imaging and modeling (only once):
# conda env create -f environment.yml

## To make a BMED365 kernel (optional):
# python -m ipykernel install --user --name bmed365 --display-name "BMED365"

## To activate the bmed365 conda environment:
# conda activate bmed365

## To update the bmed365 conda environment:
# conda env update -f environment.yml

## To remove and reinstall the bmed365 environment (if installation problems):
# conda deactivate
# conda env remove -n bmed365
# conda env create -f environment.yml
