name: bmed365ai
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipython
  - ipykernel
  - ipywidgets
  - pandas
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - git
  - pip
  - pip:
    - jupyter_ai
    - openai
    - statsmodels
    - scikit-learn
    - networkx
    - openpyxl

## Configure the Conda-environment bmed365 for data analysis, computational imaging and modeling (only once):
# conda env create -f environment_ai.yml

## To make a BMED365AI kernel (optional):
# python -m ipykernel install --user --name bmed365ai --display-name "BMED365AI"

## To activate the bmed365ai conda environment:
# conda activate bmed365ai

## To update the bmed365 conda environment:
# conda env update -f environment_ai.yml

## To remove and reinstall the bmed365ai environment (if installation problems):
# conda deactivate
# conda env remove -n bmed365ai
# conda env create -f environment_ai.yml
